services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisper
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=tiny
      - ASR_ENGINE=openai_whisper
    restart: unless-stopped

  vllm-qwen-small:
    image: dustynv/llama_cpp:r36.2.0
    container_name: vllm-qwen-small
    runtime: nvidia
    privileged: true
    ports:
      - "8001:8001"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/tegra:/usr/local/cuda/lib64
    volumes:
      - hf_cache:/root/.cache/huggingface
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra:ro
    command: 
      - python3
      - -m
      - llama_cpp.server
      - --model
      - "qwen2.5-1.5b-instruct-q4_k_m.gguf"  # Ponemos un nombre ficticio para que pase la validación
      - --hf_model_repo_id
      - "Qwen/Qwen2.5-1.5B-Instruct-GGUF"
      - --model_alias
      - "qwen"
      - --n_gpu_layers
      - "-1"
      - --host
      - 0.0.0.0
      - --port
      - "8001"
      - --n_ctx
      - "512"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/docs"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
 
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - WHISPER_API_URL=http://whisper:9000/asr
      - QWEN_HTTP_URL=http://vllm-qwen-small:8001/v1/chat/completions
      - QWEN_MODEL=Qwen/Qwen2.5-1.5B-Instruct-AWQ
      - BUFFER_WINDOW_SECONDS=90
      - MIN_ANALYSIS_INTERVAL_SECONDS=15
      - MAX_ANALYSIS_INTERVAL_SECONDS=20
      - THRESHOLD_GREEN=65
      - THRESHOLD_RED=40
      - CONFIRMATIONS_FOR_RED=2
    depends_on:
      whisper:
        condition: service_started
      vllm-qwen-small:
        condition: service_healthy
    restart: unless-stopped

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "80:80"
      - "8516:8516"
    restart: unless-stopped

volumes:
  hf_cache: